# Generated by Django 2.2.1 on 2019-09-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogindex', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='LoginUser',
        ),
        migrations.AlterModelTable(
            name='loginuser',
            table='LoginUser',
        ),
    ]
