# Generated by Django 2.2.1 on 2019-09-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogindex', '0006_auto_20190928_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='gender',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='图像'),
        ),
    ]
